name: BuildSpringApp
on:
   workflow_dispatch:

jobs:
    build-deploy:
      name: BuildSpringApp
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '21'
              cache: 'gradle'

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: docker/metadata-action@v5
                
            tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
                type=sha

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

        - name: Make gradlew executable
          run: chmod +x ./gradlew
         
        - name: Build with Gradle
          run: ./gradlew build

        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/springapp:${{ github.sha }}

        - name: login to docker hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/springapp:${{ github.sha }}
