name: Deploy to Minikube 

on: 
    workflow_dispatch:
  
jobs:
  job:
    runs-on: ubuntu-latest

    name: Deploy to minikube

    steps:

    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Check cluster
      run: kubectl get pods -A 

    - name: Deploy to minikube
      run: 
        kubectl apply -f ./minikube/springapp-deployment.yaml

        kubectl apply -f ./minikube/springapp-service.yaml

        kubectl apply -f ./minikube/springapp-ingress.yaml

    - name: Test service URLs
      run: |
          minikube service list
          minikube service springboot-app-service --url